import type { L } from "./i18n";

/** A single key/value spec line — both sides may be localized. */
export type Spec = { key: L; value: L };

export type Watch = {
  slug: string;
  brand: string;
  model: string;
  reference: L;
  year: L;
  condition: L;
  price: string;
  image: string;
  images: string[];
  intro: L;
  description: L;
  specs: Spec[];
  papers?: boolean; // box & papers indicator (default true)
  sold?: boolean;   // marks piece as sold (shown with badge, still visible)
  video?: string;   // optional video URL for the detail page gallery
  contactOnly?: boolean; // hides price, shows "more info on request"
};

export const WHATSAPP_NUMBER = "33638768692";

export const watches: Watch[] = [
  {
    slug: "rolex-submariner-14060m",
    brand: "Rolex",
    model: "Submariner",
    reference: { fr: "Submariner 14060M", en: "Submariner 14060M" },
    year: "2001",
    condition: { fr: "Excellent", en: "Excellent" },
    price: "9 680 €",
    image: "/montre/rolex/WhatsApp%20Image%202026-06-02%20at%2009.39.11.jpeg",
    images: [
      "/montre/rolex/WhatsApp%20Image%202026-06-02%20at%2009.39.11.jpeg",
      "/montre/rolex/port%C3%A9.jpeg",
      "/montre/rolex/sd.jpeg",
      "/montre/rolex/box.jpeg",
    ],
    intro: {
      fr: "Nous apprécions cette Submariner pour son état proche du neuf, son set complet et sa configuration particulièrement recherchée des collectionneurs. Cette série K de 2001 réunit plusieurs attributs emblématiques des premières 14060M, avec son cadran « Two Lines » et ses cornes percées.",
      en: "We value this Submariner for its near-mint condition, complete set and its particularly sought-after configuration among collectors. This 2001 K-series brings together several emblematic attributes of the early 14060M, with its Two Lines dial and drilled lugs.",
    },
    description: {
      fr: "Considérée comme la dernière Submariner aux proportions fines et discrètes avant l'évolution vers des générations plus imposantes, elle incarne l'équilibre parfait entre le charme des références vintage et la fiabilité des Rolex modernes. Une icône néo-vintage robuste, polyvalente et intemporelle.",
      en: "Regarded as the last Submariner with slim, discreet proportions before the evolution towards larger generations, it embodies the perfect balance between the charm of vintage references and the reliability of modern Rolex. A robust, versatile and timeless neo-vintage icon.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Rolex" },
      { key: { fr: "Modèle", en: "Model" }, value: { fr: "Submariner No Date", en: "Submariner No Date" } },
      { key: { fr: "Référence", en: "Reference" }, value: "14060M" },
      { key: { fr: "Année", en: "Year" }, value: { fr: "2001 (série K)", en: "2001 (K-series)" } },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Acier inoxydable", en: "Stainless steel" } },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "40 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Rolex calibre 3130, automatique", en: "Rolex calibre 3130, automatic" } },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Noir « Two Lines »", en: "Black \"Two Lines\"" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Lunette", en: "Bezel" }, value: { fr: "Aluminium noire, unidirectionnelle", en: "Black aluminium, unidirectional" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Oyster 93150, end-links 501B", en: "Oyster 93150, end-links 501B" } },
      { key: { fr: "Particularités", en: "Features" }, value: { fr: "Cornes percées (drilled lugs)", en: "Drilled lugs" } },
      { key: { fr: "Accessoires", en: "Accessories" }, value: { fr: "Full set", en: "Full set" } },
      { key: { fr: "Révision", en: "Service" }, value: { fr: "Rolex Service Center — 2021", en: "Rolex Service Center — 2021" } },
      { key: { fr: "État", en: "Condition" }, value: { fr: "Excellent, proche du neuf", en: "Excellent, near mint" } },
      { key: { fr: "Garantie", en: "Warranty" }, value: { fr: "1 an · maison 2121", en: "1 year · 2121 maison" } },
    ],
  },
  {
    slug: "audemars-piguet-royal-oak",
    brand: "Audemars Piguet",
    model: "Royal Oak",
    reference: "Royal Oak 56175SP",
    year: "1998",
    condition: { fr: "Excellent", en: "Excellent" },
    price: "17 800 €",
    image: "/montre/ap/WhatsApp%20Image%202026-06-02%20at%2010.08.57.jpeg",
    images: [
      "/montre/ap/WhatsApp%20Image%202026-06-02%20at%2010.08.57.jpeg",
      "/montre/ap/WhatsApp%20Image%202026-06-02%20at%2010.05.25.jpeg",
      "/montre/ap/WhatsApp%20Image%202026-06-02%20at%2010.05.37.jpeg",
      "/montre/ap/WhatsApp%20Image%202026-06-02%20at%2010.10.42.jpeg",
    ],
    intro: {
      fr: "Avec ses proportions équilibrées, son profil ultra-plat et son association d'acier et de platine, la référence 56175SP occupe une place à part dans la collection Royal Oak. Son cadran noir à chiffres romains apporte une touche d'élégance au dessin de Gérald Genta, tandis que son format de 33 mm lui confère une présence discrète au poignet.",
      en: "With its balanced proportions, ultra-flat profile and combination of steel and platinum, the 56175SP holds a special place in the Royal Oak collection. Its black dial with Roman numerals adds elegance to Gérald Genta's design, while its 33 mm format lends a discreet presence on the wrist.",
    },
    description: {
      fr: "Une référence caractéristique des productions Audemars Piguet de la fin des années 1990.",
      en: "A reference characteristic of Audemars Piguet production from the late 1990s.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Audemars Piguet" },
      { key: { fr: "Modèle", en: "Model" }, value: "Royal Oak" },
      { key: { fr: "Référence", en: "Reference" }, value: "56175SP" },
      { key: { fr: "Année", en: "Year" }, value: "1998" },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Acier inoxydable", en: "Stainless steel" } },
      { key: { fr: "Lunette", en: "Bezel" }, value: { fr: "Platine massif", en: "Solid platinum" } },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "33 mm" },
      { key: { fr: "Épaisseur", en: "Thickness" }, value: "6 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Audemars Piguet calibre 2612, quartz", en: "Audemars Piguet calibre 2612, quartz" } },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Noir à chiffres romains", en: "Black with Roman numerals" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Royal Oak intégré en acier", en: "Integrated Royal Oak steel bracelet" } },
      { key: { fr: "Fermoir", en: "Clasp" }, value: { fr: "Double boucle déployante Audemars Piguet", en: "Audemars Piguet double deployant clasp" } },
      { key: { fr: "Étanchéité", en: "Water resistance" }, value: "50 m" },
      { key: { fr: "Accessoires", en: "Accessories" }, value: { fr: "Extrait d'archives AP + boîtier de voyage AP", en: "AP archive extract + AP travel case" } },
      { key: { fr: "État", en: "Condition" }, value: { fr: "Excellent état", en: "Excellent condition" } },
      { key: { fr: "Garantie", en: "Warranty" }, value: { fr: "1 an · maison 2121", en: "1 year · 2121 maison" } },
    ],
  },
  {
    slug: "breguet-marine-3400ba",
    brand: "Breguet",
    model: "Marine",
    reference: "Marine 3400BA",
    year: { fr: "Circa 2000", en: "Circa 2000" },
    condition: { fr: "Excellent", en: "Excellent" },
    price: "8 200 €",
    image: "/montre/breguet/first.jpeg",
    images: [
      "/montre/breguet/first.jpeg",
      "/montre/breguet/de.jpeg",
      "/montre/breguet/dezs.jpeg",
      "/montre/breguet/ze.jpeg",
      "/montre/breguet/WhatsApp%20Image%202026-06-02%20at%2010.54.01.jpeg",
    ],
    intro: {
      fr: "Issue de la première génération de la collection Marine, la référence 3400BA associe les codes traditionnels de Breguet à un boîtier sport-chic de 36 mm en or jaune. Son cadran argenté guilloché à la main, ses aiguilles Breguet bleuies et son calibre automatique Breguet 517GG, dérivé du Jaeger-LeCoultre 889/2, en font l'une des références emblématiques de cette période de production.",
      en: "From the first generation of the Marine collection, the 3400BA reference combines Breguet's traditional codes with a sport-chic 36 mm yellow gold case. Its hand-guilloché silvered dial, blued Breguet hands and Breguet 517GG automatic calibre — derived from the Jaeger-LeCoultre 889/2 — make it one of the emblematic references of this production period.",
    },
    description: {
      fr: "Présentée en excellente condition, cette montre est accompagnée d'un bracelet neuf en crocodile Breguet et de sa boucle déployante Breguet en or jaune.",
      en: "Presented in excellent condition, this watch comes with a new Breguet crocodile strap and its Breguet yellow gold deployant clasp.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Breguet" },
      { key: { fr: "Modèle", en: "Model" }, value: "Marine" },
      { key: { fr: "Référence", en: "Reference" }, value: "3400BA" },
      { key: { fr: "Circa", en: "Circa" }, value: "2000" },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or jaune 18k", en: "18k yellow gold" } },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "36 mm" },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Argenté guilloché à la main", en: "Hand-guilloché silvered" } },
      { key: { fr: "Fonctions", en: "Functions" }, value: { fr: "Heures, minutes, secondes, date", en: "Hours, minutes, seconds, date" } },
      { key: { fr: "Calibre", en: "Calibre" }, value: "Breguet 517GG" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Automatique", en: "Automatic" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Crocodile Breguet (neuf)", en: "Breguet crocodile (new)" } },
      { key: { fr: "Boucle", en: "Clasp" }, value: { fr: "Déployante Breguet en or jaune", en: "Breguet yellow gold deployant" } },
      { key: { fr: "Accessoires", en: "Accessories" }, value: { fr: "Aucun", en: "None" } },
      { key: { fr: "État", en: "Condition" }, value: { fr: "Excellent", en: "Excellent" } },
      { key: { fr: "Garantie", en: "Warranty" }, value: { fr: "6 mois · maison 2121", en: "6 months · 2121 maison" } },
    ],
  },
  {
    slug: "patek-philippe-calatrava",
    brand: "Patek Philippe",
    model: "Quantième Perpétuel",
    reference: { fr: "Quantième Perpétuel 5140R-011", en: "Perpetual Calendar 5140R-011" },
    year: "2017",
    condition: { fr: "Excellent", en: "Excellent" },
    price: "52 000 €",
    image: "/montre/patek/1.jpg",
    images: [
      "/montre/patek/1.jpg",
      "/montre/patek/2.jpg",
      "/montre/patek/3.jpg",
    ],
    intro: {
      fr: "Aujourd'hui arrêtée, la référence 5140R compte parmi les quantièmes perpétuels les plus élégants de Patek Philippe. Son boîtier extra-plat de 37,2 mm en or rose abrite le calibre manufacture 240 Q à micro-rotor, reconnu pour sa finesse et son architecture raffinée.",
      en: "Now discontinued, the 5140R reference ranks among the most elegant perpetual calendars from Patek Philippe. Its extra-slim 37.2 mm rose gold case houses the in-house calibre 240 Q with micro-rotor, renowned for its refinement and sophisticated architecture.",
    },
    description: {
      fr: "Cette montre est accompagnée de sa boîte remontoir Patek Philippe, de son bracelet crocodile Patek Philippe et de sa boucle déployante en or rose.",
      en: "This watch comes with its Patek Philippe winding box, its Patek Philippe crocodile strap and its rose gold deployant clasp.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Patek Philippe" },
      { key: { fr: "Année", en: "Year" }, value: "2017" },
      { key: { fr: "Référence", en: "Reference" }, value: "5140R-001" },
      { key: { fr: "Matière", en: "Material" }, value: { fr: "Or rose 18k", en: "18k rose gold" } },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Automatique manufacture — Calibre 240 Q", en: "In-house automatic — Calibre 240 Q" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Crocodile brun Patek Philippe, boucle déployante or rose", en: "Brown Patek Philippe crocodile, rose gold deployant clasp" } },
      { key: { fr: "Dimensions", en: "Dimensions" }, value: "37,2 mm / 20 mm" },
      { key: { fr: "Étanchéité", en: "Water resistance" }, value: "30 m" },
      { key: { fr: "Accessoires", en: "Accessories" }, value: { fr: "Boîte remontoir Patek Philippe", en: "Patek Philippe winding box" } },
      { key: { fr: "Garantie", en: "Warranty" }, value: { fr: "6 mois · maison 2121", en: "6 months · 2121 maison" } },
    ],
  },
  {
    slug: "vacheron-constantin-malachite-1970s",
    brand: "Vacheron Constantin",
    model: "Malachite",
    reference: { fr: "Or jaune 18k, Circa 1970", en: "18k yellow gold, Circa 1970" },
    year: { fr: "Circa 1970", en: "Circa 1970" },
    condition: { fr: "Bon état", en: "Good condition" },
    price: "4 750 €",
    image: "/montre/vacheronmalachite/first.jpeg",
    images: [
      "/montre/vacheronmalachite/first.jpeg",
      "/montre/vacheronmalachite/vahcee.jpeg",
      "/montre/vacheronmalachite/zed.jpeg",
      "/montre/vacheronmalachite/dcvc.jpeg",
      "/montre/vacheronmalachite/WhatsApp%20Image%202026-06-02%20at%2011.09.45.jpeg",
    ],
    intro: {
      fr: "Au cours des années 1970, les grandes manufactures genevoises explorent de nouveaux codes esthétiques, mêlant horlogerie et joaillerie. Cette Vacheron Constantin en or jaune 18 carats en est une parfaite illustration. Son cadran en malachite naturelle apporte profondeur et caractère à une architecture entièrement pensée autour du bracelet intégré tressé.",
      en: "During the 1970s, the great Genevan manufacturers explored new aesthetic codes, blending watchmaking and jewellery. This Vacheron Constantin in 18-carat yellow gold is a perfect example. Its natural malachite dial brings depth and character to an architecture entirely conceived around the integrated woven bracelet.",
    },
    description: {
      fr: "Une pièce typique de cette période créative, où le travail de l'or occupe autant d'importance que la mesure du temps.",
      en: "A piece typical of this creative period, where goldsmithing holds as much importance as timekeeping.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Vacheron Constantin" },
      { key: { fr: "Circa", en: "Circa" }, value: "1970" },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or jaune 18 carats", en: "18-carat yellow gold" } },
      { key: { fr: "Dimensions", en: "Dimensions" }, value: "24 × 24 mm" },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Malachite naturelle", en: "Natural malachite" } },
      { key: { fr: "Calibre", en: "Calibre" }, value: "Vacheron Constantin K1050/B" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Remontage manuel", en: "Manual winding" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Intégré tressé, or jaune 18 carats", en: "Integrated woven, 18-carat yellow gold" } },
      { key: { fr: "Fermoir", en: "Clasp" }, value: { fr: "Invisible, or jaune 18 carats", en: "Hidden, 18-carat yellow gold" } },
      { key: { fr: "Longueur bracelet", en: "Bracelet length" }, value: { fr: "Environ 16 cm", en: "Approximately 16 cm" } },
      { key: { fr: "Accessoires", en: "Accessories" }, value: { fr: "Aucun", en: "None" } },
      { key: { fr: "Garantie", en: "Warranty" }, value: { fr: "6 mois · maison 2121", en: "6 months · 2121 maison" } },
    ],
  },
  {
    slug: "cartier-tortue",
    brand: "Cartier",
    model: "Mini Tortue",
    reference: { fr: "Mini Tortue — Or jaune 18k", en: "Mini Tortue — 18k yellow gold" },
    year: { fr: "Vintage", en: "Vintage" },
    condition: { fr: "Très bon", en: "Very good" },
    price: "4 800 €",
    image: "/montre/verte/1.jpg",
    images: [
      "/montre/verte/1.jpg",
      "/montre/verte/2.jpg",
    ],
    intro: {
      fr: "Véritable icône de la maison Cartier, la Mini Tortue se distingue par son boîtier en forme de tortue, une silhouette élégante et intemporelle qui compte parmi les créations les plus emblématiques de la marque.",
      en: "A true icon of the Cartier maison, the Mini Tortue stands out with its distinctive tortue-shaped case — an elegant and timeless silhouette among the brand's most emblematic creations.",
    },
    description: {
      fr: "Réalisée en or jaune 18 carats, cette version de 24 mm est animée par un mouvement à quartz et montée sur un bracelet en cuir avec boucle Cartier. Une montre discrète et raffinée, idéale pour les amateurs de montres de forme et du style intemporel propre à Cartier.",
      en: "Crafted in 18-carat yellow gold, this 24 mm version is powered by a quartz movement and fitted with a leather strap with Cartier buckle. A discreet and refined watch, ideal for connoisseurs of shaped watches and the timeless style that defines Cartier.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Cartier" },
      { key: { fr: "Matière", en: "Material" }, value: { fr: "Or jaune 18 carats", en: "18-carat yellow gold" } },
      { key: { fr: "Dimensions", en: "Dimensions" }, value: "24 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Quartz", en: "Quartz" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Cuir", en: "Leather" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Boucle ardillon Cartier or jaune 18 carats", en: "Cartier 18-carat yellow gold pin buckle" } },
      { key: { fr: "Garantie", en: "Warranty" }, value: { fr: "6 mois · maison 2121", en: "6 months · 2121 maison" } },
    ],
  },
  {
    slug: "rolex-day-date-1803",
    brand: "Rolex",
    model: "Day-Date",
    reference: "Day-Date 1803",
    year: "1973",
    condition: { fr: "Excellent", en: "Excellent" },
    price: "11 700 €",
    contactOnly: true,
    image: "/montre/roro/ds.jpeg",
    images: [
      "/montre/roro/ds.jpeg",
      "/montre/roro/WhatsApp%20Image%202026-06-02%20at%2010.29.36.jpeg",
    ],
    video: "/montre/roro/videororo.mp4",
    intro: {
      fr: "Produite en 1973, cette Rolex Day-Date référence 1803 est réalisée en or blanc 18 carats. Elle présente un cadran argenté d'origine avec aiguilles assorties. Son boîtier a conservé des proportions particulièrement généreuses et sa lunette cannelée d'origine reste bien définie. L'ensemble est présenté en excellente condition.",
      en: "Produced in 1973, this Rolex Day-Date reference 1803 is crafted in 18-carat white gold. It features an original silvered dial with matching hands. The case has retained particularly generous proportions and its original fluted bezel remains well-defined. The whole is presented in excellent condition.",
    },
    description: {
      fr: "La montre est montée sur un bracelet neuf en crocodile bleu marine et équipée d'une boucle ardillon Rolex en acier.",
      en: "The watch is fitted with a new navy blue crocodile strap and a Rolex steel pin buckle.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Rolex" },
      { key: { fr: "Modèle", en: "Model" }, value: "Day-Date" },
      { key: { fr: "Référence", en: "Reference" }, value: "1803" },
      { key: { fr: "Numéro de série", en: "Serial" }, value: "363XXXX" },
      { key: { fr: "Année", en: "Year" }, value: "1973" },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or blanc 18k", en: "18k white gold" } },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "36 mm" },
      { key: { fr: "Lunette", en: "Bezel" }, value: { fr: "Cannelée en or blanc", en: "Fluted white gold" } },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Argenté d'origine", en: "Original silvered" } },
      { key: { fr: "Aiguilles", en: "Hands" }, value: { fr: "Assorties au cadran", en: "Matching dial" } },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Automatique", en: "Automatic" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Crocodile bleu marine (neuf)", en: "Navy blue crocodile (new)" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Ardillon Rolex en acier", en: "Rolex steel pin buckle" } },
      { key: { fr: "Accessoires", en: "Accessories" }, value: { fr: "Aucun", en: "None" } },
      { key: { fr: "État", en: "Condition" }, value: { fr: "Excellent", en: "Excellent" } },
      { key: { fr: "Garantie", en: "Warranty" }, value: { fr: "6 mois · maison 2121", en: "6 months · 2121 maison" } },
    ],
  },
  {
    slug: "patek-philippe-golden-ellipse-5028g",
    brand: "Patek Philippe",
    model: "Golden Ellipse",
    reference: "Golden Ellipse 5028G",
    year: "2002",
    condition: { fr: "Excellent", en: "Excellent" },
    price: "Vendue",
    sold: true,
    image: "/montre/patek2/WhatsApp%20Image%202026-06-02%20at%2010.20.55.jpeg",
    images: [
      "/montre/patek2/WhatsApp%20Image%202026-06-02%20at%2010.20.55.jpeg",
      "/montre/patek2/d.jpeg",
    ],
    intro: {
      fr: "Avec son cadran noir à chiffres arabes et sa petite seconde, la référence 5028G se distingue nettement des Golden Ellipse traditionnelles. Produite à moins de 500 exemplaires selon les estimations communément admises par les collectionneurs, elle associe l'élégance intemporelle du boîtier Ellipse au calibre automatique 240 à micro-rotor, l'un des mouvements les plus emblématiques de Patek Philippe.",
      en: "With its black dial with Arabic numerals and small seconds, the 5028G stands clearly apart from traditional Golden Ellipses. Produced in fewer than 500 examples according to estimates widely accepted among collectors, it pairs the timeless elegance of the Ellipse case with the automatic calibre 240 micro-rotor, one of Patek Philippe's most iconic movements.",
    },
    description: {
      fr: "Une référence confidentielle et recherchée, appréciée pour son esthétique singulière au sein de la collection Golden Ellipse.",
      en: "A discreet and sought-after reference, valued for its singular aesthetic within the Golden Ellipse collection.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Patek Philippe" },
      { key: { fr: "Modèle", en: "Model" }, value: "Golden Ellipse" },
      { key: { fr: "Référence", en: "Reference" }, value: "5028G" },
      { key: { fr: "Année", en: "Year" }, value: "2002" },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or gris 18k", en: "18k white gold" } },
      { key: { fr: "Dimensions", en: "Dimensions" }, value: "31 × 35 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Patek Philippe calibre 240 PS, automatique à micro-rotor", en: "Patek Philippe calibre 240 PS, automatic micro-rotor" } },
      { key: { fr: "Fonctions", en: "Functions" }, value: { fr: "Heures, minutes, petite seconde", en: "Hours, minutes, small seconds" } },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Noir à chiffres arabes blancs", en: "Black with white Arabic numerals" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Cuir", en: "Leather" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Patek Philippe en or gris 18k", en: "Patek Philippe in 18k white gold" } },
      { key: { fr: "Accessoires", en: "Accessories" }, value: { fr: "Extrait d'archives Patek Philippe", en: "Patek Philippe archive extract" } },
      { key: { fr: "État", en: "Condition" }, value: { fr: "Excellent état", en: "Excellent condition" } },
    ],
  },
  {
    slug: "cartier-mini-vendome-18k",
    brand: "Cartier",
    model: "Mini Vendôme",
    reference: { fr: "Mini Vendôme — Or jaune 18k", en: "Mini Vendôme — 18k yellow gold" },
    year: { fr: "Circa années 1990", en: "Circa 1990s" },
    condition: { fr: "Très bon", en: "Very good" },
    price: "Vendue",
    sold: true,
    image: "/montre/cartiervendo/WhatsApp%20Image%202026-06-02%20at%2011.25.33.jpeg",
    images: [
      "/montre/cartiervendo/WhatsApp%20Image%202026-06-02%20at%2011.25.33.jpeg",
      "/montre/cartiervendo/2.jpeg",
    ],
    intro: {
      fr: "Avec son boîtier rond inspiré de la place Vendôme et ses attaches mobiles emblématiques, la Mini Vendôme fait partie des créations les plus élégantes de Cartier. Dans cette version en or jaune 18 carats de seulement 19 mm, elle réunit tous les codes de la maison : cadran à chiffres romains, aiguilles bleuies et cabochon saphir.",
      en: "With its round case inspired by the Place Vendôme and its emblematic mobile lugs, the Mini Vendôme ranks among Cartier's most elegant creations. In this 18-carat yellow gold version of just 19 mm, it brings together all the codes of the maison: Roman numeral dial, blued hands and sapphire cabochon.",
    },
    description: {
      fr: "Une montre délicate et intemporelle, devenue un classique du Cartier vintage.",
      en: "A delicate and timeless watch, now a classic of vintage Cartier.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Cartier" },
      { key: { fr: "Modèle", en: "Model" }, value: "Mini Vendôme" },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or jaune 18 carats", en: "18-carat yellow gold" } },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "19 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Quartz", en: "Quartz" } },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Blanc à chiffres romains", en: "White with Roman numerals" } },
      { key: { fr: "Aiguilles", en: "Hands" }, value: { fr: "Acier bleui", en: "Blued steel" } },
      { key: { fr: "Couronne", en: "Crown" }, value: { fr: "Cabochon saphir", en: "Sapphire cabochon" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Cuir", en: "Leather" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Ardillon", en: "Pin buckle" } },
      { key: { fr: "Circa", en: "Circa" }, value: { fr: "Années 1990", en: "1990s" } },
    ],
  },
  {
    slug: "breguet-classique-coussin-3160ba",
    brand: "Breguet",
    model: "Classique Coussin",
    reference: "Classique Coussin 3160BA",
    year: { fr: "Circa années 1990", en: "Circa 1990s" },
    condition: { fr: "Excellent", en: "Excellent" },
    price: "Vendue",
    sold: true,
    image: "/montre/okay/1.jpeg",
    images: [
      "/montre/okay/1.jpeg",
      "/montre/okay/2.jpeg",
      "/montre/okay/3.jpeg",
      "/montre/okay/4.jpeg",
      "/montre/okay/5.jpeg",
      "/montre/okay/6.jpeg",
    ],
    intro: {
      fr: "Produite durant l'ère Chaumet–Daniel Roth, la référence 3160BA réunit plusieurs éléments devenus rares chez Breguet : un boîtier coussin en or jaune, un cadran guilloché à la main et le calibre Frédéric Piguet 71 à micro-rotor. Très peu vue sur le marché aujourd'hui, elle compte parmi les références les plus confidentielles de cette période.",
      en: "Produced during the Chaumet–Daniel Roth era, the 3160BA reference brings together several elements that have become rare at Breguet: a yellow gold cushion case, a hand-guilloché dial and the Frédéric Piguet 71 micro-rotor calibre. Seldom seen on the market today, it ranks among the most confidential references of this period.",
    },
    description: {
      fr: "Une montre extrêmement rare, représentative de l'une des époques les plus appréciées par les collectionneurs de Breguet.",
      en: "An extremely rare watch, representative of one of the eras most cherished by Breguet collectors.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Breguet" },
      { key: { fr: "Modèle", en: "Model" }, value: "Classique Coussin" },
      { key: { fr: "Référence", en: "Reference" }, value: "3160BA" },
      { key: { fr: "Circa", en: "Circa" }, value: { fr: "Années 1990", en: "1990s" } },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or jaune 18 carats", en: "18-carat yellow gold" } },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "31 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Automatique", en: "Automatic" } },
      { key: { fr: "Calibre", en: "Calibre" }, value: { fr: "Frédéric Piguet 71 à micro-rotor", en: "Frédéric Piguet 71 micro-rotor" } },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Guilloché main", en: "Hand-guilloché" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Cuir", en: "Leather" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Ardillon en or jaune 18 carats", en: "18-carat yellow gold pin buckle" } },
    ],
  },
  {
    slug: "cartier-mini-baignoire-2369",
    brand: "Cartier",
    model: "Mini Baignoire",
    reference: "Mini Baignoire 2369",
    year: { fr: "Circa début 2000", en: "Circa early 2000s" },
    condition: { fr: "Excellent", en: "Excellent" },
    price: "Vendue",
    sold: true,
    image: "/montre/handzer/WhatsApp%20Image%202026-06-02%20at%2011.37.53.jpeg",
    images: [
      "/montre/handzer/WhatsApp%20Image%202026-06-02%20at%2011.37.53.jpeg",
      "/montre/handzer/2.jpeg",
      "/montre/handzer/3.jpeg",
    ],
    intro: {
      fr: "Déclinaison miniature de l'un des modèles les plus emblématiques de Cartier, la Mini Baignoire 2369 reprend les lignes de la Baignoire dans un format de seulement 18 mm. Son boîtier en or blanc 18 carats et son cadran à chiffres romains lui confèrent une présence discrète et intemporelle.",
      en: "A miniature version of one of Cartier's most emblematic models, the Mini Baignoire 2369 takes up the lines of the Baignoire in a format of just 18 mm. Its 18-carat white gold case and Roman numeral dial give it a discreet and timeless presence.",
    },
    description: {
      fr: "Bien moins fréquente sur le marché que les versions en or jaune, cette référence figure parmi les Mini Baignoire vintage les plus recherchées aujourd'hui.",
      en: "Far less frequent on the market than the yellow gold versions, this reference is among the most sought-after vintage Mini Baignoires today.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Cartier" },
      { key: { fr: "Modèle", en: "Model" }, value: "Mini Baignoire" },
      { key: { fr: "Référence", en: "Reference" }, value: "2369" },
      { key: { fr: "Circa", en: "Circa" }, value: { fr: "Début des années 2000", en: "Early 2000s" } },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or blanc 18 carats", en: "18-carat white gold" } },
      { key: { fr: "Dimensions", en: "Dimensions" }, value: "18 × 24 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Quartz", en: "Quartz" } },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Blanc à chiffres romains", en: "White with Roman numerals" } },
      { key: { fr: "Aiguilles", en: "Hands" }, value: { fr: "Acier bleui", en: "Blued steel" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Cuir", en: "Leather" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Ardillon Cartier", en: "Cartier pin buckle" } },
    ],
  },
  {
    slug: "vacheron-constantin-patrimony-92240",
    brand: "Vacheron Constantin",
    model: "Patrimony",
    reference: "Patrimony 92240/000J",
    year: { fr: "Circa années 1990", en: "Circa 1990s" },
    condition: { fr: "Excellent", en: "Excellent" },
    price: "7 200 €",
    image: "/montre/constanzer/WhatsApp%20Image%202026-06-02%20at%2011.44.45.jpeg",
    images: [
      "/montre/constanzer/WhatsApp%20Image%202026-06-02%20at%2011.44.45.jpeg",
      "/montre/constanzer/2.jpeg",
    ],
    intro: {
      fr: "Issue de la collection Les Essentielles, la référence 92240 illustre l'approche la plus classique de Vacheron Constantin. Son boîtier en or jaune 18 carats, son cadran à petite seconde et son mouvement à remontage manuel en font une montre fidèle aux grands codes de l'horlogerie genevoise.",
      en: "From the Les Essentielles collection, the 92240 reference illustrates Vacheron Constantin's most classical approach. Its 18-carat yellow gold case, small seconds dial and manual-winding movement make it a watch faithful to the great codes of Genevan watchmaking.",
    },
    description: {
      fr: "Une référence discrète, peu commune sur le marché, appréciée pour ses proportions équilibrées et sa sobriété.",
      en: "A discreet reference, uncommon on the market, valued for its balanced proportions and sobriety.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Vacheron Constantin" },
      { key: { fr: "Modèle", en: "Model" }, value: "Patrimony" },
      { key: { fr: "Référence", en: "Reference" }, value: "92240/000J" },
      { key: { fr: "Circa", en: "Circa" }, value: { fr: "Années 1990", en: "1990s" } },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or jaune 18 carats", en: "18-carat yellow gold" } },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "32,5 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Remontage manuel", en: "Manual winding" } },
      { key: { fr: "Calibre", en: "Calibre" }, value: "1014/1" },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Blanc, petite seconde", en: "White, small seconds" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Cuir", en: "Leather" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Ardillon en or jaune 18 carats", en: "18-carat yellow gold pin buckle" } },
      { key: { fr: "Étanchéité", en: "Water resistance" }, value: "30 m" },
      { key: { fr: "Garantie", en: "Warranty" }, value: { fr: "6 mois · maison 2121", en: "6 months · 2121 maison" } },
    ],
  },
  {
    slug: "breguet-classique-triple-calendrier-serpentine-3047ba",
    brand: "Breguet",
    model: "Classique Triple Calendrier Phase de Lune « Serpentine »",
    reference: { fr: "Classique Triple Calendrier « Serpentine » 3047BA", en: "Classique Triple Calendar \"Serpentine\" 3047BA" },
    year: { fr: "Circa années 1990", en: "Circa 1990s" },
    condition: { fr: "Excellent", en: "Excellent" },
    price: "Vendue",
    sold: true,
    image: "/montre/braguette/WhatsApp%20Image%202026-06-02%20at%2011.53.48.jpeg",
    images: [
      "/montre/braguette/WhatsApp%20Image%202026-06-02%20at%2011.53.48.jpeg",
      "/montre/braguette/3.jpeg",
      "/montre/braguette/4.jpeg",
    ],
    intro: {
      fr: "Issue de l'ère Chaumet–Daniel Roth, la référence 3047BA compte parmi les Breguet les plus rares de la période. Son cadran guilloché à la main affiche le jour, le mois, la phase de lune et la date par aiguille serpentine, une configuration devenue emblématique auprès des collectionneurs.",
      en: "From the Chaumet–Daniel Roth era, the 3047BA reference ranks among the rarest Breguets of the period. Its hand-guilloché dial displays the day, the month, the moon phase and the date via a serpentine hand — a configuration that has become emblematic among collectors.",
    },
    description: {
      fr: "Animée par un mouvement automatique à micro-rotor gravé à la main et produite à moins de 100 exemplaires selon les estimations communément admises, elle représente l'une des expressions les plus abouties de la Breguet néo-vintage.",
      en: "Driven by a hand-engraved micro-rotor automatic movement and produced in fewer than 100 examples according to widely accepted estimates, it represents one of the most accomplished expressions of neo-vintage Breguet.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Breguet" },
      { key: { fr: "Modèle", en: "Model" }, value: { fr: "Classique Triple Calendrier Phase de Lune « Serpentine »", en: "Classique Triple Calendar Moon Phase \"Serpentine\"" } },
      { key: { fr: "Référence", en: "Reference" }, value: "3047BA" },
      { key: { fr: "Circa", en: "Circa" }, value: { fr: "Années 1990", en: "1990s" } },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or jaune 18 carats", en: "18-carat yellow gold" } },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "36 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Automatique", en: "Automatic" } },
      { key: { fr: "Calibre", en: "Calibre" }, value: "Frédéric Piguet P.71 (Breguet 502 QS)" },
      { key: { fr: "Fonctions", en: "Functions" }, value: { fr: "Heures, minutes, triple calendrier, phase de lune", en: "Hours, minutes, triple calendar, moon phase" } },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Guilloché main", en: "Hand-guilloché" } },
      { key: { fr: "Aiguilles", en: "Hands" }, value: { fr: "Acier bleui", en: "Blued steel" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Fond", en: "Caseback" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Cuir", en: "Leather" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Ardillon en or jaune 18 carats", en: "18-carat yellow gold pin buckle" } },
      { key: { fr: "Production estimée", en: "Estimated production" }, value: { fr: "Moins de 100 exemplaires (estimations des collectionneurs et spécialistes de la marque)", en: "Fewer than 100 examples (per collector and specialist estimates)" } },
    ],
  },
  {
    slug: "patek-philippe-calatrava-3520j",
    brand: "Patek Philippe",
    model: "Calatrava",
    reference: "Calatrava 3520J",
    year: { fr: "Circa années 1980–1990", en: "Circa 1980s–1990s" },
    condition: { fr: "Excellent", en: "Excellent" },
    price: "Vendue",
    sold: true,
    image: "/montre/calzer/WhatsApp%20Image%202026-06-02%20at%2011.56.21.jpeg",
    images: [
      "/montre/calzer/WhatsApp%20Image%202026-06-02%20at%2011.56.21.jpeg",
    ],
    intro: {
      fr: "Produite durant les années 1980 et 1990, la référence 3520J illustre la vision de Patek Philippe de la montre habillée. Son boîtier en or jaune 18 carats, son cadran blanc opalin et son calibre automatique à micro-rotor réunissent les éléments qui ont fait la réputation de la Calatrava.",
      en: "Produced during the 1980s and 1990s, the 3520J reference illustrates Patek Philippe's vision of the dress watch. Its 18-carat yellow gold case, opaline white dial and automatic micro-rotor calibre bring together the elements that built the Calatrava's reputation.",
    },
    description: {
      fr: "Une référence aujourd'hui recherchée pour ses proportions classiques et son mouvement extra-plat.",
      en: "A reference sought-after today for its classical proportions and extra-thin movement.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Patek Philippe" },
      { key: { fr: "Modèle", en: "Model" }, value: "Calatrava" },
      { key: { fr: "Référence", en: "Reference" }, value: "3520J" },
      { key: { fr: "Circa", en: "Circa" }, value: { fr: "Années 1980–1990", en: "1980s–1990s" } },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or jaune 18 carats", en: "18-carat yellow gold" } },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "32 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Automatique", en: "Automatic" } },
      { key: { fr: "Calibre", en: "Calibre" }, value: "240" },
      { key: { fr: "Réserve de marche", en: "Power reserve" }, value: { fr: "Environ 48 heures", en: "Approximately 48 hours" } },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Blanc opalin", en: "Opaline white" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Cuir", en: "Leather" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Ardillon en or jaune 18 carats", en: "18-carat yellow gold pin buckle" } },
    ],
  },
  {
    slug: "audemars-piguet-quantieme-perpetuel-25657or",
    brand: "Audemars Piguet",
    model: "Quantième Perpétuel",
    reference: "Quantième Perpétuel 25657OR",
    year: { fr: "Circa 1990", en: "Circa 1990" },
    condition: { fr: "Excellent", en: "Excellent" },
    price: "Vendue",
    sold: true,
    image: "/montre/quantzer/WhatsApp%20Image%202026-06-02%20at%2012.04.42.jpeg",
    images: [
      "/montre/quantzer/WhatsApp%20Image%202026-06-02%20at%2012.04.42.jpeg",
      "/montre/quantzer/2.jpeg",
    ],
    intro: {
      fr: "Lancée au début des années 1980, la référence 25657OR appartient à la génération de calendriers perpétuels qui a marqué le retour de la haute horlogerie mécanique. Son boîtier de 36 mm en or rose 18 carats renferme le calibre 2120/2800, l'un des mouvements à calendrier perpétuel les plus importants de son époque.",
      en: "Launched in the early 1980s, the 25657OR reference belongs to the generation of perpetual calendars that marked the return of mechanical haute horlogerie. Its 36 mm 18-carat rose gold case houses the calibre 2120/2800, one of the most important perpetual calendar movements of its era.",
    },
    description: {
      fr: "Produite à seulement 362 exemplaires en or rose, cette référence compte parmi les Audemars Piguet les plus rares et les plus recherchées de la période.",
      en: "Produced in only 362 examples in rose gold, this reference ranks among the rarest and most sought-after Audemars Piguets of the period.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Audemars Piguet" },
      { key: { fr: "Modèle", en: "Model" }, value: "Quantième Perpétuel" },
      { key: { fr: "Référence", en: "Reference" }, value: "25657OR" },
      { key: { fr: "Circa", en: "Circa" }, value: "1990" },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or rose 18 carats", en: "18-carat rose gold" } },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "36 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Automatique", en: "Automatic" } },
      { key: { fr: "Calibre", en: "Calibre" }, value: "2120/2800" },
      { key: { fr: "Fonctions", en: "Functions" }, value: { fr: "Heures, minutes, jour, date, mois, année bissextile, phase de lune, calendrier perpétuel", en: "Hours, minutes, day, date, month, leap year, moon phase, perpetual calendar" } },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Blanc opalin", en: "Opaline white" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Crocodile Audemars Piguet bleu marine", en: "Audemars Piguet navy blue crocodile" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Ardillon en or rose 18 carats", en: "18-carat rose gold pin buckle" } },
      { key: { fr: "Production", en: "Production" }, value: { fr: "362 exemplaires en or rose", en: "362 examples in rose gold" } },
    ],
  },
  {
    slug: "jaeger-lecoultre-reverso-tribute-duoface-q3908420",
    brand: "Jaeger-LeCoultre",
    model: "Reverso Tribute Duoface",
    reference: "Reverso Tribute Duoface Q3908420",
    year: "2016",
    condition: { fr: "Excellent", en: "Excellent" },
    price: "Vendue",
    sold: true,
    image: "/montre/reverso/1.jpeg",
    images: [
      "/montre/reverso/1.jpeg",
      "/montre/reverso/2.jpeg",
    ],
    intro: {
      fr: "Inspirée des premières Reverso des années 1930, la référence Q3908420 associe les codes historiques du modèle à la complication Duoface, permettant l'affichage d'un second fuseau horaire sur le cadran verso. Son boîtier réversible en acier, son cadran argenté et son mouvement manufacture à remontage manuel en font l'une des interprétations contemporaines les plus réussies de la Reverso.",
      en: "Inspired by the first Reversos of the 1930s, the Q3908420 reference combines the model's historical codes with the Duoface complication, displaying a second time zone on the reverse dial. Its reversible steel case, silvered dial and in-house manual-winding movement make it one of the most accomplished contemporary interpretations of the Reverso.",
    },
    description: {
      fr: "Une référence devenue incontournable au sein de la collection Tribute.",
      en: "A reference that has become essential within the Tribute collection.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Jaeger-LeCoultre" },
      { key: { fr: "Modèle", en: "Model" }, value: "Reverso Tribute Duoface" },
      { key: { fr: "Référence", en: "Reference" }, value: "Q3908420" },
      { key: { fr: "Circa", en: "Circa" }, value: "2016" },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Acier inoxydable", en: "Stainless steel" } },
      { key: { fr: "Dimensions", en: "Dimensions" }, value: "42,9 × 25,5 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Remontage manuel", en: "Manual winding" } },
      { key: { fr: "Calibre", en: "Calibre" }, value: "Jaeger-LeCoultre 854A/2" },
      { key: { fr: "Réserve de marche", en: "Power reserve" }, value: "42 h" },
      { key: { fr: "Fonctions", en: "Functions" }, value: { fr: "Heures, minutes, petite seconde, second fuseau horaire, indicateur jour/nuit", en: "Hours, minutes, small seconds, second time zone, day/night indicator" } },
      { key: { fr: "Cadran recto", en: "Front dial" }, value: { fr: "Argenté", en: "Silvered" } },
      { key: { fr: "Cadran verso", en: "Reverse dial" }, value: { fr: "Bleu", en: "Blue" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Cuir bleu", en: "Blue leather" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Déployante acier", en: "Steel deployant" } },
      { key: { fr: "Étanchéité", en: "Water resistance" }, value: "30 m" },
    ],
  },
  {
    slug: "rolex-cosmograph-daytona-126500ln",
    brand: "Rolex",
    model: "Cosmograph Daytona",
    reference: "Cosmograph Daytona 126500LN",
    year: "2023",
    condition: { fr: "Excellent", en: "Excellent" },
    price: "Vendue",
    sold: true,
    image: "/montre/cosmo/WhatsApp%20Image%202026-06-02%20at%2012.14.30.jpeg",
    images: [
      "/montre/cosmo/WhatsApp%20Image%202026-06-02%20at%2012.14.30.jpeg",
    ],
    intro: {
      fr: "Présentée en 2023, la référence 126500LN reprend les codes du Daytona moderne tout en introduisant le nouveau calibre 4131. Son boîtier Oystersteel de 40 mm, sa lunette Cerachrom noire et son chronographe automatique en font l'une des références les plus convoitées du catalogue Rolex.",
      en: "Unveiled in 2023, the 126500LN reference takes up the codes of the modern Daytona while introducing the new calibre 4131. Its 40 mm Oystersteel case, black Cerachrom bezel and automatic chronograph make it one of the most coveted references in the Rolex catalogue.",
    },
    description: {
      fr: "Évolution directe de la 116500LN, elle conserve l'esprit du Daytona tout en bénéficiant d'améliorations techniques et esthétiques discrètes.",
      en: "A direct evolution of the 116500LN, it retains the spirit of the Daytona while benefiting from discreet technical and aesthetic refinements.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Rolex" },
      { key: { fr: "Modèle", en: "Model" }, value: "Cosmograph Daytona" },
      { key: { fr: "Référence", en: "Reference" }, value: "126500LN" },
      { key: { fr: "Année", en: "Year" }, value: "2023" },
      { key: { fr: "Boîtier", en: "Case" }, value: "Oystersteel" },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "40 mm" },
      { key: { fr: "Épaisseur", en: "Thickness" }, value: "11,9 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Automatique", en: "Automatic" } },
      { key: { fr: "Calibre", en: "Calibre" }, value: "4131" },
      { key: { fr: "Réserve de marche", en: "Power reserve" }, value: { fr: "Environ 72 heures", en: "Approximately 72 hours" } },
      { key: { fr: "Fonctions", en: "Functions" }, value: { fr: "Heures, minutes, petite seconde, chronographe", en: "Hours, minutes, small seconds, chronograph" } },
      { key: { fr: "Lunette", en: "Bezel" }, value: { fr: "Cerachrom noire avec échelle tachymétrique", en: "Black Cerachrom with tachymetric scale" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Oyster en acier", en: "Steel Oyster" } },
      { key: { fr: "Boucle", en: "Clasp" }, value: { fr: "Oysterlock avec Easylink", en: "Oysterlock with Easylink" } },
      { key: { fr: "Étanchéité", en: "Water resistance" }, value: "100 m" },
    ],
  },
  {
    slug: "daniel-roth-millenium-moonphase-power-reserve-0357bcsl",
    brand: "Daniel Roth",
    model: "Millenium Moonphase & Power Reserve",
    reference: "Millenium 0357BCSL",
    year: { fr: "Circa 2000", en: "Circa 2000" },
    condition: { fr: "Excellent", en: "Excellent" },
    price: "Vendue",
    sold: true,
    image: "/montre/daniel/1.jpeg",
    images: [
      "/montre/daniel/1.jpeg",
      "/montre/daniel/2.jpeg",
      "/montre/daniel/3.jpeg",
      "/montre/daniel/4.jpeg",
    ],
    intro: {
      fr: "Créée pour célébrer le passage à l'an 2000, la référence 0357BCSL réunit plusieurs éléments caractéristiques de l'univers Daniel Roth : le boîtier double ellipse, le cadran guilloché à la main et un mouvement à remontage manuel associé à une phase de lune et un indicateur de réserve de marche.",
      en: "Created to celebrate the turn of the year 2000, the 0357BCSL reference brings together several elements characteristic of the Daniel Roth universe: the double-ellipse case, the hand-guilloché dial and a manual-winding movement paired with a moon phase and power reserve indicator.",
    },
    description: {
      fr: "Produite à seulement 50 exemplaires, elle compte parmi les références les plus rares de la période précédant l'intégration de la marque au sein de Bulgari.",
      en: "Produced in only 50 examples, it ranks among the rarest references of the period preceding the brand's integration within Bulgari.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Daniel Roth" },
      { key: { fr: "Modèle", en: "Model" }, value: "Millenium Moonphase & Power Reserve" },
      { key: { fr: "Référence", en: "Reference" }, value: "0357BCSL" },
      { key: { fr: "Circa", en: "Circa" }, value: "2000" },
      { key: { fr: "Production", en: "Production" }, value: { fr: "50 exemplaires", en: "50 examples" } },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Or blanc 18 carats", en: "18-carat white gold" } },
      { key: { fr: "Dimensions", en: "Dimensions" }, value: "35 × 38 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Remontage manuel", en: "Manual winding" } },
      { key: { fr: "Fonctions", en: "Functions" }, value: { fr: "Heures, minutes, phase de lune, réserve de marche", en: "Hours, minutes, moon phase, power reserve" } },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Guilloché main", en: "Hand-guilloché" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Cuir", en: "Leather" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Ardillon en or blanc 18 carats", en: "18-carat white gold pin buckle" } },
      { key: { fr: "Accessoires", en: "Accessories" }, value: { fr: "Full set", en: "Full set" } },
    ],
  },
  {
    slug: "patek-philippe-aquanaut-5065a",
    brand: "Patek Philippe",
    model: "Aquanaut",
    reference: "Aquanaut 5065A",
    year: { fr: "Circa 2000", en: "Circa 2000" },
    condition: { fr: "Excellent", en: "Excellent" },
    price: "Vendue",
    sold: true,
    image: "/montre/patzer/WhatsApp%20Image%202026-06-02%20at%2011.49.11.jpeg",
    images: [
      "/montre/patzer/WhatsApp%20Image%202026-06-02%20at%2011.49.11.jpeg",
      "/montre/patzer/1.jpeg",
    ],
    intro: {
      fr: "Produite autour de l'an 2000, la référence 5065A marque les débuts de l'Aquanaut moderne. Avec son boîtier de 38 mm, son cadran gaufré et son bracelet composite assorti, elle introduit une esthétique plus décontractée au sein de l'univers Patek Philippe.",
      en: "Produced around the year 2000, the 5065A reference marks the beginnings of the modern Aquanaut. With its 38 mm case, embossed dial and matching composite strap, it introduces a more casual aesthetic within the Patek Philippe universe.",
    },
    description: {
      fr: "Produite durant une période relativement courte, elle est aujourd'hui l'une des références les plus recherchées de la première génération Aquanaut.",
      en: "Produced for a relatively short period, it is today one of the most sought-after references of the first-generation Aquanaut.",
    },
    specs: [
      { key: { fr: "Marque", en: "Brand" }, value: "Patek Philippe" },
      { key: { fr: "Modèle", en: "Model" }, value: "Aquanaut" },
      { key: { fr: "Référence", en: "Reference" }, value: "5065A" },
      { key: { fr: "Circa", en: "Circa" }, value: "2000" },
      { key: { fr: "Boîtier", en: "Case" }, value: { fr: "Acier inoxydable", en: "Stainless steel" } },
      { key: { fr: "Diamètre", en: "Diameter" }, value: "38 mm" },
      { key: { fr: "Mouvement", en: "Movement" }, value: { fr: "Automatique", en: "Automatic" } },
      { key: { fr: "Calibre", en: "Calibre" }, value: "315 SC" },
      { key: { fr: "Cadran", en: "Dial" }, value: { fr: "Noir gaufré", en: "Black embossed" } },
      { key: { fr: "Verre", en: "Crystal" }, value: { fr: "Saphir", en: "Sapphire" } },
      { key: { fr: "Bracelet", en: "Bracelet" }, value: { fr: "Composite Patek Philippe", en: "Patek Philippe composite" } },
      { key: { fr: "Boucle", en: "Buckle" }, value: { fr: "Déployante Patek Philippe", en: "Patek Philippe deployant" } },
      { key: { fr: "Étanchéité", en: "Water resistance" }, value: "120 m" },
      { key: { fr: "Accessoires", en: "Accessories" }, value: { fr: "Full set", en: "Full set" } },
    ],
  },
];

export function getWatch(slug: string): Watch | undefined {
  return watches.find((w) => w.slug === slug);
}

export function buildWhatsAppLink(watch: Watch) {
  // Kept for backward compatibility — components now build the link via i18n.
  const message = `Bonjour 2121, je suis intéressé par la ${watch.brand} ${watch.model}. Pourriez-vous me communiquer plus d'informations ?`;
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
}
